version: '3'

services:
  mongo:
    image: mongo:4
    env_file: ../../.env
    volumes:
      - /var/lib/guov/mongo:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=guov
      - MONGO_INITDB_ROOT_PASSWORD=guov
    ports:
      - 27017:27017
  postgres:
    image: postgres:10
    volumes:
      - /var/lib/guov/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
  nginx:
    image: nginx:1.14
    network_mode: host
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ../../client/build:/app/build