version: '3'

services:
  mongo:
    image: mongo:4
    env_file: ../../.env
    volumes:
      - ./db/mongo:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=guov
      - MONGO_INITDB_ROOT_PASSWORD=guov
    ports:
      - ${MONGO_PORT}:27017
  redis:
    image: redis:4
    ports:
      - 6379:6379
  nginx:
    image: nginx:1.14
    network_mode: host
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80