version: '3'

services:
  main:
    env_file: ../.env
    image: docker.scis.xyz/kanban-backend:${BACKEND_IMAGE_VERSION}
    network_mode: host
    environment:
    - MICROSERVICES=main
  chat:
    env_file: ../.env
    image: docker.scis.xyz/kanban-backend:${BACKEND_IMAGE_VERSION}
    network_mode: host
    environment:
      - MICROSERVICES=chat