version: '3'

services:
  mongo:
    image: mongo:4
    volumes:
      - /var/lib/guov/mongo:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=guov
      - MONGO_INITDB_ROOT_PASSWORD=guov
    ports:
      - 27017:27017
    restart: always
  postgres:
    image: postgres:10
    volumes:
      - /var/lib/guov/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=guov
      - POSTGRES_PASSWORD=guov
      - POSTGRES_DATABASE=fias
    restart: always
  nginx:
    image: nginx:1.14
    network_mode: host
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ../../client/build:/app/build
      - /tmp/pics/:/app/images/
    restart: always
