version: '3'

services:
  mongo:
    image: mongo:4
    env_file: ../../.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=guov
      - MONGO_INITDB_ROOT_PASSWORD=guov
    ports:
      - ${MONGO_PORT}:27017
  redis:
    image: redis:4
    ports:
      - 6379:6379