version: '3'

services:
  postgres:
    env_file: ../.env
    image: postgres:10
    volumes:
      - ./db/postgres:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
  mongo:
    image: mongo:4
    env_file: ../.env
    volumes:
      - ./db/mongo:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=guov
      - MONGO_INITDB_ROOT_PASSWORD=guov
    ports:
      - ${MONGO_PORT}:27017
  redis:
    image: redis:4
    ports:
      - 6379:6379
  nginx:
    image: nginx:1.14